name: MyOccupancy CICD

on: [push]
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          ssh-agent: yes
          script: |
            cd ~/Projects/occupancy-backend
            eval (ssh-agent -c)
            ssh-add ~/.ssh/personal_server
            git pull
            sudo systemctl restart myoccupancy.service
